CREATE TABLE TRANSACTION (
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  RELATED_TRANSACTION_ID VARCHAR(255) NOT NULL,
  DESCRIPTION VARCHAR(255) NOT NULL,
  INSTALLMENT INT NOT NULL DEFAULT 1,
  AMOUNT DECIMAL(10, 2) NOT NULL,
  CURRENCY VARCHAR(255) NOT NULL,
  TYPE VARCHAR(255) NOT NULL,
  CATEGORY VARCHAR(255) NOT NULL,
  EXPECTED_PAYMENT_DATE DATE NOT NULL,
  PAYMENT_DATE DATE,
  CREATED_DATE TIMESTAMP NOT NULL,
  LAST_MODIFIED_DATE TIMESTAMP NOT NULL
);
